config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace :private do
    root 'categories#index'
    resources :categories, except: %i[show] do
      post 'commit', on: :collection
      resources :products, shallow: true
    end
  end

  root 'categories#index'
  resources :categories, only: %i[index show]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :timeoutable,
         :trackable,
         :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  SLUG_BLACK_LIST = %w[about admin api billing blog buy demo dev download email faq ftp help
                       imap mail me my pop pop3 pricing sftp shop smtp staging support wiki
                       ww www wwww].freeze

  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  # As of FriendlyId 5.0, slugs are only generated when the slug field is nil.
  # If you want a slug to be regenerated,set the slug field to nil
  before_validation :set_nil_slug
  friendly_id :name, use: :slugged

  validates :name, :slug, uniqueness: true
  validates :slug, exclusion: { in: SLUG_BLACK_LIST }

  has_many :products
  has_ancestry orphan_strategy: :rootify

  def set_nil_slug
    self.slug = nil if self.slug.blank?
  end

  def normalize_friendly_id(string)
    string.to_slug.normalize.to_s
  end
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  # As of FriendlyId 5.0, slugs are only generated when the slug field is nil.
  # If you want a slug to be regenerated,set the slug field to nil
  before_validation :set_nil_slug
  friendly_id :name, use: :slugged

  validates :name, uniqueness: true
  validates :slug, exclusion: { in: SLUG_BLACK_LIST }
  validates :image, blob: { content_type: :image }

  belongs_to :category
  has_one_attached :image, dependent: :purge_now

  def set_nil_slug
    self.slug = nil if self.slug.blank?
  end

  def normalize_friendly_id(string)
    string.to_slug.normalize.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def index
    @categories = Category.roots
  end

  def show; end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/private/categories_controller.rb
class Private::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    @category = Category.last
  end

  def new
    @category = Category.new
  end



  def commit
    category_updater = CategoryUpdateAncestryService.execute(params)

    category_updater.success?
    respond_to do |format|
      if category_updater.success?
        format.json { render json: { code: 200 }, status: 200 }
      else
        format.json { render json: { code:500, data: category_updater.errors }, status: 500}
      end
    end
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to private_root_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to private_root_path, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to private_root_path, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :ancestry, :slug)
  end

end

app/controllers/private/products_controller.rb
class Private::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:create]

  def index
    @category = Category.friendly.find(params[:category_id])
    @products = @category.products
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end


  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to private_category_products_path(@product.category), notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to private_product_path(@product), notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to private_root_path, notice: 'Product was successfully destroyed.' }
    end
  end

  private

  def set_product
    @product = Product.friendly.find(params[:id])
  end

  def set_category
    @category = Category.friendly.find(params[:category_id])
  end

  def product_params
    params.require(:product).permit(:name, :slug, :category, :category_id, :image, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in show alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def nested_categories(categories)
    content_tag(:ol, class: 'dd-list') do
      categories.map do |category, sub_categories|
        content_tag(:li, class: 'dd-item', data: {id: category.id} ) do
          render(category) + nested_categories(sub_categories)
        end
      end.join.html_safe
    end
  end

  def parent_category(category)
    category.parent.present? ? category.parent.id : nil
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image(product)
    product.image.present? ? product.image : asset_path('no_photo.jpg')
  end
end

app/views/categories/_category.html.haml
= link_to category.name, category, class: 'list-group-item list-group-item-action'

app/views/categories/_product.html.haml
.col-md-4
  .card
    .card-body
      = image_tag product_image(product), class: 'card-img-top'
      %h5.card-title= product.name
      %p.card-text= product.description
      .btn.btn-primary Buy this

app/views/categories/index.html.haml
.row
  .col-md-12
    %h4
      Select a product categories
    = render @categories

app/views/categories/show.html.haml
.row.justify-content-center
  .col-md
    %h3 Category:  #{@category.name}
    - if @category.children?
      .list-group
        = render partial: 'categories/category', collection:  @category.children
    - if @category.products.any?
      %h5
        Products:
      .card-group
        = render partial: 'categories/product', collection: @category.products

    = link_to 'Back to categories', categories_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8",
      "http-equiv" => "Content-Type"}/
    %title MolinosAncestry
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
  %ul.nav
    - if admin_signed_in?
      %li.nav-item= link_to 'Home', private_root_path, class: 'nav-link'
      %li.nav-item= link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'nav-link'
    - else
      %li.nav-item= link_to 'Home', root_path, class: 'nav-link'
  .container
    = bootstrap_flash
    = yield

app/views/private/categories/_category.html.haml
.dd-handle
  .dd-base
    = category.name
  .dd-nodrag
    = link_to fa_icon('eye'), private_category_products_path(category),
        data: {toggle: 'tooltip', placement: 'top'}, title: 'Show category products'
    = link_to fa_icon('pencil'), edit_private_category_path(category)
    = link_to  fa_icon('trash'), category, method: :delete, data: { confirm: 'Delete category?' }

app/views/private/categories/_form.html.haml
= form_with(model: category,
   local: true,
   url: (category.new_record? ? private_categories_path : private_category_path(category))) do |form|
  - if category.errors.any?
    #error_explanation
      %h2
        = pluralize(category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - category.errors.full_messages.each do |message|
          %li= message

  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .form-group
    = form.label :slug
    = form.text_field :slug, class: 'form-control'
  .form-group
    = form.label :ancestry
    = form.collection_select :ancestry, Category.all,
            :id, :name,
            { selected: parent_category(category) },
            { class: 'form-control' }

  = form.submit class: "btn btn-primary"

app/views/private/categories/edit.html.haml
%h1 Editing Category
= render 'form', category: @category
= link_to 'Back', private_root_path

app/views/private/categories/index.html.haml
%h1 Categories
.nestable-menu
  %button{type: "button",
    data: {action: "expand-all"},
    class: "btn btn-sm btn-secondary"} Expand All
  %button{type: "button",
    data: {action: "collapse-all"},
    class: "btn btn-sm btn-secondary"} Collapse All
.dd
  = nested_categories @categories.arrange
%hr
= link_to 'New Category', new_private_category_path, class: "btn btn-primary"
- if @category.present?
  = link_to 'New product', new_private_category_product_path(@category), class: "btn btn-primary"
%button{type:"button", class: "btn btn-primary btn-update-categories"} Update categories

app/views/private/categories/new.html.haml
%h1 Create new Category
= render 'form', category: @category
= link_to 'Back', private_categories_path

app/views/private/products/_form.html.haml
= form_with(model: product,
    url: (product.new_record? ? private_category_products_path : private_product_path(product)),
    local: true) do |form|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  .form-group
    = form.label :slug
    = form.text_field :slug, class: 'form-control'
  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control'
  .form-group
    = form.label :category_id
    = form.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-control'}
  .form-group
    = form.label :image, 'Products photo'
    = form.file_field :image, class: 'form-control-file'

  = form.submit class: "btn btn-primary"

app/views/private/products/_product.html.haml
.card.w-25
  .card-body
    = image_tag product_image(product), class: 'card-img-top'
    %h5.card-title= product.name
    %p.card-text= product.description

app/views/private/products/edit.html.haml
%h1 Editing Product
= render 'form', product: @product

= link_to 'Show', private_product_path(@product)
|
= link_to 'Back',private_category_products_path(@product.category)

app/views/private/products/index.html.haml
%h1 Products in #{@category.name} category
%table.table
  %thead
    %tr
      %th Name
      %th Slug
      %th Action
  %tbody
    - if @products.any?
      - @products.each do |product|
        %tr
          %td= product.name
          %td= product.slug
          %td
            = link_to fa_icon('eye'), private_product_path(product)
            = link_to fa_icon('pencil'), edit_private_product_path(product)
            = link_to fa_icon('trash'), private_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }
    - else
      %p No Products
%br/
.nav
  = link_to 'New Product', new_private_category_product_path, class: "nav-link"
  = link_to 'Back to categories',  private_categories_path, class: "nav-link"

app/views/private/products/new.html.haml
%h1 New Product
= render 'form', product: @product
= link_to 'Back', private_root_path

app/views/private/products/show.html.haml
.row.justify-content-center
  .col-md-6
    .card
      .card-header= @product.name
      = image_tag product_image(@product), class: 'card-img-top'
      .card-body
        .card-text
          Description
          = @product.description
      .card-body
        Category name:
        = @product.category.name
      .card-body
        = link_to 'Edit product', edit_private_product_path(@product), class: 'card-link'
        = link_to 'To category',  private_category_products_path(@product.category), class: 'card-link'